name: Package Release
on:
  push:
    branches:
      - "releases/**"
  workflow_dispatch:

jobs:
  package-release:
    strategy:
      matrix:
        platform:
          - requirements: win-linux-cuda.txt
            os: windows-latest
            filename: windows-cuda
          - requirements: win-dml.txt
            os: windows-latest
            filename:  windows-directml
          - requirements: mac-mps-cpu.txt
            os: macos-14
            filename: macos-arm
        version:
          - python: '3.10'
            filename_suffix: ''
          - python: '3.11'
            filename_suffix: '-4-1'
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: dream_textures
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version.python }}
          cache: 'pip'
          cache-dependency-path: '**/${{ matrix.platform.requirements }}'
      - name: Install dependencies into target
        shell: bash
        run: 'python -m pip install -r requirements/${{ matrix.platform.requirements }} --no-cache-dir --target .python_dependencies'
        working-directory: dream_textures
      - name: Zip dependencies with long paths
        shell: bash
        run: 'python ./dream_textures/scripts/zip_dependencies.py'
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: dream_textures-${{ matrix.platform.filename }}${{ matrix.version.filename_suffix }}.zip
          exclusions: '*.git*'
      - name: Archive and upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dream_textures-${{ matrix.platform.filename }}${{ matrix.version.filename_suffix }}
          path: dream_textures-${{ matrix.platform.filename }}${{ matrix.version.filename_suffix }}.zip